CREATE SCHEMA SIERRA_SCHEMA;
SET search_path TO SIERRA_SCHEMA;

CREATE TABLE SIERRA_SCHEMA.USERS (
        ID_USER VARCHAR(36) NOT NULL,
        USER_NAME VARCHAR(100) NOT NULL,
        FIRST_NAME VARCHAR(100) NOT NULL,
        LAST_NAME VARCHAR(100),
        EMAIL VARCHAR(100) NOT NULL,
        CREATION_DATE TIMESTAMP DEFAULT current_timestamp,
        ACTIVE BOOLEAN NOT NULL DEFAULT true
);

ALTER TABLE SIERRA_SCHEMA.USERS 
    ADD CONSTRAINT USERS_PK_ID_USER PRIMARY KEY(ID_USER); 

CREATE TABLE SIERRA_SCHEMA.ROLES (
    ID_ROLE VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL
);

ALTER TABLE SIERRA_SCHEMA.ROLES 
    ADD CONSTRAINT ROLES_PK_ID_ROLE PRIMARY KEY(ID_ROLE); 


CREATE TABLE SIERRA_SCHEMA.USERS_ROLES (
    ID_USER VARCHAR(36) NOT NULL,
    ID_ROLE VARCHAR(36) NOT NULL,
    ASSIGNMENT_DATE TIMESTAMP DEFAULT current_timestamp NOT NULL
);

ALTER TABLE SIERRA_SCHEMA.USERS_ROLES 
    ADD CONSTRAINT USERS_ROLES_PK_ID_USER_ID_ROLE PRIMARY KEY(ID_USER, ID_ROLE); 

ALTER TABLE SIERRA_SCHEMA.USERS_ROLES 
    ADD CONSTRAINT USERS_ROLES_FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES SIERRA_SCHEMA.USERS (ID_USER);
   
ALTER TABLE SIERRA_SCHEMA.USERS_ROLES 
    ADD CONSTRAINT USERS_ROLES_FK_ID_ROLE FOREIGN KEY (ID_ROLE) REFERENCES SIERRA_SCHEMA.ROLES (ID_ROLE); 

CREATE TABLE SIERRA_SCHEMA.PERMISSIONS (
    ID_PERMISSION VARCHAR(36) NOT NULL,
    NAME VARCHAR NOT NULL
);

ALTER TABLE SIERRA_SCHEMA.PERMISSIONS 
    ADD CONSTRAINT PERMISSIONS_PK_ID_PERMISSION PRIMARY KEY(ID_PERMISSION); 

CREATE TABLE SIERRA_SCHEMA.ROLES_PERMISSIONS (
    ID_ROLE VARCHAR(36) NOT NULL,
    ID_PERMISSION VARCHAR(36) NOT NULL
);

ALTER TABLE SIERRA_SCHEMA.ROLES_PERMISSIONS 
    ADD CONSTRAINT ROLES_PERMISSIONS_PK_ID_ROLE_ID_PERMISSION PRIMARY KEY(ID_ROLE, ID_PERMISSION); 

ALTER TABLE SIERRA_SCHEMA.ROLES_PERMISSIONS 
    ADD CONSTRAINT ROLES_PERMISSIONS_FK_ID_ROLE FOREIGN KEY (ID_ROLE) REFERENCES SIERRA_SCHEMA.ROLES (ID_ROLE); 
ALTER TABLE SIERRA_SCHEMA.ROLES_PERMISSIONS 
    ADD CONSTRAINT ROLES_PERMISSIONS_FK_ID_PERMISSION FOREIGN KEY (ID_PERMISSION) REFERENCES SIERRA_SCHEMA.PERMISSIONS (ID_PERMISSION); 


CREATE TABLE SIERRA_SCHEMA.CONVERSATIONS (
    ID_CONVERSATION VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP
);

ALTER TABLE SIERRA_SCHEMA.CONVERSATIONS
    ADD CONSTRAINT RCONVERSATIONS_PK_ID_CONVERSATION PRIMARY KEY(ID_CONVERSATION); 


CREATE TABLE SIERRA_SCHEMA.MESSAGES (
    ID_MESSAGE VARCHAR(36) NOT NULL,
    ID_USER VARCHAR(36) NOT NULL,
    ID_CONVERSATION VARCHAR(36) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    SENT_DATE TIMESTAMP DEFAULT current_timestamp
);

ALTER TABLE SIERRA_SCHEMA.MESSAGES
    ADD CONSTRAINT MESSAGES_PK_ID_MESSAGE PRIMARY KEY(ID_MESSAGE); 

ALTER TABLE SIERRA_SCHEMA.MESSAGES 
    ADD CONSTRAINT MESSAGES_FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES SIERRA_SCHEMA.USERS(ID_USER); 
ALTER TABLE SIERRA_SCHEMA.MESSAGES 
    ADD CONSTRAINT MESSAGES_FK_ID_CONVERSATION FOREIGN KEY (ID_CONVERSATION) REFERENCES SIERRA_SCHEMA.CONVERSATIONS(ID_CONVERSATION); 


CREATE TABLE SIERRA_SCHEMA.USERS_CONVERSATIONS (
    ID_USER VARCHAR(36) NOT NULL,
    ID_CONVERSATION VARCHAR(36) NOT NULL
);

ALTER TABLE SIERRA_SCHEMA.USERS_CONVERSATIONS 
    ADD CONSTRAINT USERS_CONVERSATIONS_PK_ID_USER_ID_CONVERSATION PRIMARY KEY(ID_USER,ID_CONVERSATION); 


ALTER TABLE SIERRA_SCHEMA.USERS_CONVERSATIONS 
    ADD CONSTRAINT USERS_CONVERSATIONS_FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES SIERRA_SCHEMA.USERS(ID_USER); 
ALTER TABLE SIERRA_SCHEMA.USERS_CONVERSATIONS 
    ADD CONSTRAINT USERS_CONVERSATIONS_FK_ID_CONVERSATION FOREIGN KEY (ID_CONVERSATION) REFERENCES SIERRA_SCHEMA.CONVERSATIONS(ID_CONVERSATION); 

ALTER DEFAULT PRIVILEGES IN SCHEMA sierra_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.conversations TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.messages TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.permissions TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.roles TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.roles_permissions TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.users TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.users_conversations TO "app-role";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sierra_schema.users_roles TO "app-role";
