package sierra.model.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// default package
// Generated 2 mar 2024, 22:16:23 by Hibernate Tools 6.3.1.Final

/**
 * TestTable generated by hbm2java
 */
@Entity
@Table(name = "test_table")
public class TestTable implements java.io.Serializable {

	@Id
	private String id;
	private String nombre;

	public TestTable() {
	}

	public TestTable(String id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
